apiVersion: v1
kind: ConfigMap
metadata:
  name: meteoride-config
  namespace: default
data:
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8080"
  REDIS_URL: "redis://meteoride-redis:6379/0"
  CACHE_TTL_SECONDS: "900"
  CACHE_GEOHASH_PRECISION: "5"
